read in other available sensors
actigraph/actiapi pull request #18
Opened 2024-03-15 18:33 UTC by m-patterson-wearable

read in other available sensors from api.

Copied the sensor names from api documentaiton

2024-03-17 21:23 UTC, rouzbeh commented on actiapi/v3.py
> +            "ppg-green (25hz)", "ppg-green-100-hz",
I think the name is "ppg-green", not "ppg-green (25hz)".

2024-03-17 21:24 UTC, rouzbeh requested changes
I think the name is not correct. I have tested "ppg-green" and know it works.

2024-03-26 20:30 UTC, m-patterson-wearable commented
Documentation in the AG API page says this:
![Screen Shot 2024-03-26 at 4 27 45 PM](https://github.com/actigraph/actiapi/assets/52720149/66d5dd7f-22ba-4448-a255-cbc1002d6382)

https://github.com/actigraph/CentrePoint3APIDocumentation/blob/main/sections/data_access_files.md

2024-04-02 17:49 UTC, rouzbeh commented
> Documentation in the AG API page says this: ![Screen Shot 2024-03-26 at 4 27 45 PM](https://private-user-images.githubusercontent.com/52720149/317029350-66d5dd7f-22ba-4448-a255-cbc1002d6382.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwODAzNDgsIm5iZiI6MTcxMjA4MDA0OCwicGF0aCI6Ii81MjcyMDE0OS8zMTcwMjkzNTAtNjZkNWRkN2YtMjJiYS00NDQ4LWEyNTUtY2JjMTAwMmQ2MzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE3NDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NTcxZTliYjVjYWYwNGI1NDNiM2NlNTlkOTU5YjA5YzAyNjVmMDQxNTE2NTUwNTNiMjBjMDhkOTdhZmU0NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NDV12EXdounQJkxQQx3XSM9HMZMqqrvaL2opr3wm1qI)
> 
> https://github.com/actigraph/CentrePoint3APIDocumentation/blob/main/sections/data_access_files.md

Yes, but that is poorly worded. `ppg-green` gives you 25Hz PPG data, as opposed to `ppg-green-100-hz`. They first created `ppg-green` before they realized there would be other frequencies.

2024-05-02 07:42 UTC, rouzbeh approved these changes

2024-05-02 07:42 UTC, merged